/**
 * Evoke Website API
 * This API provides endpoints used by the Evoke demoparty website. <br><br><a href='https://www.evoke.eu/imprint/'>Imprint</a><br><a href='https://www.evoke.eu/privacy/'>Privacy Information</a>
 *
 * OpenAPI spec version: 0.1.0
 * Contact: api@evoke.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EvokeWebsiteApi);
  }
}(this, function(expect, EvokeWebsiteApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EvokeWebsiteApi.RegistrationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RegistrationApi', function() {
    describe('createRegistration', function() {
      it('should call createRegistration successfully', function(done) {
        //uncomment below and update the code to test createRegistration
        //instance.createRegistration(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRegistration', function() {
      it('should call deleteRegistration successfully', function(done) {
        //uncomment below and update the code to test deleteRegistration
        //instance.deleteRegistration(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('numberOfRegistrations', function() {
      it('should call numberOfRegistrations successfully', function(done) {
        //uncomment below and update the code to test numberOfRegistrations
        //instance.numberOfRegistrations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('showAllCountries', function() {
      it('should call showAllCountries successfully', function(done) {
        //uncomment below and update the code to test showAllCountries
        //instance.showAllCountries(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('showAllRegistrations', function() {
      it('should call showAllRegistrations successfully', function(done) {
        //uncomment below and update the code to test showAllRegistrations
        //instance.showAllRegistrations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
